[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
protocol = { path = "../protocol" }
tokio = { version = "1.34.0", features = ["full"] }
